spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/info?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  mvc:
    static-path-pattern: /**
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.example.demo.entity
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
logging:
  level:
    root: warn
    com.example.demo.entity: trace
  pattern:
    console: '%p%m%n'